layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: YangCazz
  # dribbble: YangCazz
  # facebook: YangCazz
  # hackerrank: YangCazz
  # instagram: YangCazz
  # keybase: YangCazz
  linkedin: YangCazz
  # mastodon: YangCazz
  # medium: YangCazz
  # stackoverflow: your_user_id
  # telegram: YangCazz
  twitter: YangCazz
  # unsplash: YangCazz
  # vk: YangCazz
  # website: http://your_website_url
  youtube: YangCazz

topics:
  - name: JavaScript
    web_url: https://github.com/topics/javascript
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/javascript/javascript.png

  - name: Python
    web_url: https://github.com/topics/python
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/python/python.png

  - name: React
    web_url: https://github.com/topics/react
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/react/react.png

  - name: Node.js
    web_url: https://github.com/topics/nodejs
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/nodejs/nodejs.png

  - name: Web Development
    web_url: https://github.com/topics/web-development
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/web-development/web-development.png

  - name: Machine Learning
    web_url: https://github.com/topics/machine-learning
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/machine-learning/machine-learning.png
